services:
  - type: web
    name: blendpilot-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: blendpilot-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXP
        value: 15m
      - key: JWT_REFRESH_EXP
        value: 7d
      - key: BCRYPT_SALT_ROUND
        value: 10
      - key: BASE_URL
        value: https://your-app-name.onrender.com
      - key: CORS_ORIGIN
        value: https://your-frontend-url.vercel.app
